### ISSUE TITLE
What's the catch?

### ISSUE THREAD

**Issue by fulldecent** [ontometrics/JSONCoding#11]
This is the obvious way to do JSON, why aren't there 70 million people using this? Is there some type of catch? Or is there some other solution that came out after this?

**Comment by codeslubber** [comment]
There is no catch. We have used this in several of our own projects. Thanks for the sentiments! If you have issues getting it going, let us know. It's pretty quick.

**Comment by fulldecent** [comment]
Ok, it looks like the catch is classes need to be named by convention and source code should be in English language.

I have gone with the solution to add these functions to each class:

```
+ (CLASS *)CLASSFromDictionary:(NSDictionary *)dictionary;
- (NSDictionary *)toDictionary;
+ (CLASS *)CLASSFromJSON:(NSData *)JSON;
- (NSData *)toJSON;
```

**Comment by codeslubber** [comment]
Not sure why I didn't see this...

We are changing that. Adding methods to each class undoes the whole point of NSCoding. You'll see our solution shortly, I think you'll like.

Thanks.
