### ISSUE TITLE
How might one use this library together with Mantle?

### ISSUE THREAD

**Issue by hokster7** [ontometrics/JSONCoding#18]
I'm just looking at both options at the minute — does Mantle strictly supersede the capabilities of this library?

**Comment by hokster7** [comment]
I think I've established in MantleFramework/Mantle#280 that Mantle has its specific uses — it writes the coder methods for the user, and also lets developers specify mappings between the object and the external representation. However, object references are not preserved.

**Comment by codeslubber** [comment]
Read the other thread. Interesting. Could not tell though, did you decide to use this?

**Comment by hokster7** [comment]
I ended up not using this library, because AutoCoding+HRCoder does the same job in a more modular way.

However, notably, neither this library nor the AutoCoding+HRCoder combination support encoding graphs of `NSManagedObject`, together with their relationships.
