### ISSUE TITLE
Deserializing empty arrays causes out of bounds exception to be thrown

### ISSUE THREAD

**Issue by MikaelSetterberg** [ontometrics/JSONCoding#7]
Issue: Deserializing JSON formatted data such as' {"E":0,"D":"{\"emptyArray\":[]}"} causes a crash in JSONDecoder.m

In decodeArrayOfClass: (Class) class there is no check whether the returned array is empty or not. This causes an out of bounds exception to be thrown.

Code causing exception: innerDictionary = [(NSArray *)[self topJsonObject] objectAtIndex:0];

Adding a check just before seems to do the trick:
<fix>
NSArray *theArray = (NSArray *) [self topJsonObject];
if ([theArray count] == 0)
  return [NSArray new];
</fix>

Otherwise, kudos for some nice piece of code!

/M

**Comment by codeslubber** [comment]
Sorry took me a while to see this Mikael! I will fix this immediately. (And turn on email notifications on this repo.. ??) Thanks for the kind words.

**Comment by codeslubber** [comment]
Ok. this is fixed on master.
